# Generated by CodiumAI
from Models.DataTrip import DataTrip
import json
import os


class TestDataTrip:
    # Tests that an instance of DataTrip is created with all attributes set to non-None values
    def test_create_instance_all_non_none(self):
        data_trip = DataTrip(1, 2, 3, 4, 5, 6)
        assert data_trip.total_time == 1
        assert data_trip.stop_time == 2
        assert data_trip.move_time == 3
        assert data_trip.bill_stop == 4
        assert data_trip.bill_move == 5
        assert data_trip.bill_total == 6

    # Tests that save_history_to_file method saves valid JSON data to a file named 'history.json' when the file is empty
    def test_save_history_to_file_empty_file(self):
        data_trip = DataTrip(1, 2, 3, 4, 5, 6)
        json_data = data_trip.data_to_json()
        if os.path.isfile("history.json"):
            os.remove("history.json")
        data_trip.save_history_to_file(json_data)
        with open("history.json", "r") as file:
            content = file.read()
            assert content.startswith("[")
            assert content.endswith("]")
            assert json.loads(content) == [json.loads(json_data)]
